### ISSUE TITLE
Hyprland  `wayland.windowManager.hyprland.settings` does not exist. 

### ISSUE THREAD

**Issue by wanderer** [danth/stylix#152]
I'm getting the following error when trying to use hyprland
```
     error: The option `wayland.windowManager.hyprland.settings' does not exist
```
in file 
```
/nix/store/w4x7vhmj184brhk7jllscm4z8rjnk5xp-modules/hyprland/hm.nix                                                                              
```

**Comment by danth** [comment]
Hi, Stylix assumes you're using the new Hyprland module which is built in to recent versions of Home Manager. The module from the Hyprland flake doesn't support the option we use.

You should be able to switch to the new module easily because it's backwards compatible with the old module - all you need to do is remove the Hyprland flake and update Home Manager.

**Comment by wanderer** [comment]
Thanks!

**Comment by realsnick** [comment]
removing the hyprland module did the trick for me and my system is back to normal.  Thank you!

**Comment by jh-devv** [comment]
@danth This issue persists still for me, Does hyprland need to be installed on homemanager?

**Comment by jh-devv** [comment]
> Hi, Stylix assumes you're using the new Hyprland module which is built in to recent versions of Home Manager.** The module from the Hyprland flake doesn't support the option we use.**
> 
> You should be able to switch to the new module easily because it's backwards compatible with the old module - all you need to do is remove the Hyprland flake and update Home Manager.

Could you please explain this?

**Comment by 0x4d6165** [comment]
This has been happening for me even without the hyprland module and without hyprland being installed at all.
