### ISSUE TITLE
doc: add GitHub issue templates

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#326]
# About 

This is a tracking issue for extending and providing GitHub issue templates for every available issue label.

Closes: https://github.com/danth/stylix/issues/268

# Steps 

- [ ] https://github.com/danth/stylix/pull/516

# Unresolved Questions 

- [ ] What labels should be added or removed?

**Comment by danth** [comment]
Note: "good first issue" and "help wanted" should not have their own templates, since these are additional labels to be added to issues in other categories. (They only exist since GitHub creates them by default.)

We may also want to adjust the labelling, for example by splitting "feature" into sub-categories:

- New targets
- Adjusting existing targets
- New features in `/stylix`

**Comment by danth** [comment]
I would also recommend collecting the templates into a single merge, since it could be confusing for contributors to only see templates for certain issues while we are still busy creating them.

**Comment by trueNAHO** [comment]
Superseded-by: https://github.com/danth/stylix/pull/516
