### ISSUE TITLE
zellij: `programs.zellij.*` no longer exists.

### ISSUE THREAD

**Issue by Industrial** [danth/stylix#352]
Hi.

Zellij is now packaged in nixpkgs: https://github.com/NixOS/nixpkgs/blob/73e7e2108ab07de34aa9ea4d70242d9ff5fb7f04/pkgs/tools/misc/zellij/default.nix

I see it is configured as such: https://github.com/danth/stylix/blob/0fe277a3641a849478a94c7900c2d5a90609a306/modules/zellij/hm.nix#L8

1. I'm not sure why that doesn't raise an error.
2. It results in this:
![Screenshot_2024-04-25_22-42-50](https://github.com/danth/stylix/assets/3317/20a17cd1-f0d3-4e6e-8e0b-f26b7000d394)

Not really that nice :/

**Comment by trueNAHO** [comment]
> Zellij is now packaged in nixpkgs: https://github.com/NixOS/nixpkgs/blob/73e7e2108ab07de34aa9ea4d70242d9ff5fb7f04/pkgs/tools/misc/zellij/default.nix

AFAIK, it has been since https://github.com/NixOS/nixpkgs/commit/f1df273a67a2b17f97bc833b76639cda3cdd5d9a.

> I see it is configured as such:
>
> https://github.com/danth/stylix/blob/0fe277a3641a849478a94c7900c2d5a90609a306/modules/zellij/hm.nix#L8
>
> 1. I'm not sure why that doesn't raise an error.

Stylix currently locks Home Manager to the `820be197ccf3adaad9a8856ef255c13b6cc561a6` revision:

https://github.com/danth/stylix/blob/0fe277a3641a849478a94c7900c2d5a90609a306/flake.lock#L166-L185

This points to the valid `programs.zellij` attribute set:

https://github.com/nix-community/home-manager/blob/820be197ccf3adaad9a8856ef255c13b6cc561a6/modules/programs/zellij.nix#L14

Could you elaborate on the expected error?

> 2. It results in this:
>    ![Screenshot_2024-04-25_22-42-50](https://private-user-images.githubusercontent.com/3317/325765172-20a17cd1-f0d3-4e6e-8e0b-f26b7000d394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTkzODcsIm5iZiI6MTcxNDExOTA4NywicGF0aCI6Ii8zMzE3LzMyNTc2NTE3Mi0yMGExN2NkMS1mMGQzLTRlNmUtOGUwYi1mMjZiNzAwMGQzOTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMDgxMTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZkM2VjOTFjOTAzNzliZDAwZjU0NzZhNTc3OTllOTM4ZmQ3ZDUwZjk2MDU1MGU0YjQ3MTc0OTIxMDE5MDcxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m1CxUnDwTsYcpAMCHWO65IP3qfIXCCUZRmqCqRZaSGg)
>
> Not really that nice :/

Could you elaborate what specific elements are unpleasing?

**Comment by afresquet** [comment]
Can't reproduce this myself, `zellij` works fine for me

`nixpkgs`: `58a1abdbae3217ca6b702f03d3b35125d88a2994`
`home-manager`: `2af7c78b7bb9cf18406a193eba13ef9f99388f49`
`stylix`: `0fe277a3641a849478a94c7900c2d5a90609a306`
`zellij`: `0.40.0`

**Comment by trueNAHO** [comment]
To: @Industrial

Feel free to reopen this issue, if it is still a problem.

**Comment by danth** [comment]
Possibly related to #379
