### ISSUE TITLE
chromium: `programs.chromium.enable` now installs chromium

### ISSUE THREAD

**Issue by danth** [danth/stylix#500]
See https://github.com/NixOS/nixpkgs/commit/93b6400ff55782bdcdc68df89168fe498ae6494a

**Comment by trueNAHO** [comment]
Resolved by https://github.com/NixOS/nixpkgs/pull/334726.

**Comment by panchoh** [comment]
After reading the comments in the linked issues, I learned that the fix was simply to define: `programs.chromium.package = pkgs.emptyDirectory`. :exploding_head:  It's an [actual package](https://search.nixos.org/packages?channel=unstable&show=emptyDirectory&from=0&size=50&sort=relevance&type=packages&query=emptyDirectory).
