### ISSUE TITLE
stylix: re-add `flake-utils` dependency

### ISSUE THREAD

**Issue by trueNAHO** [danth/stylix#512]
To: @danth

Why was the `flake-utils` dependency removed in commit ff5da2914cfc ("Remove dependency on flake-utils :heavy_minus_sign:")?

Some of its functionality, like [handling the `--impure` flag](https://github.com/numtide/flake-utils/pull/115), are neat but would be too costly to re-implement on our side.

Re-adding `flake-utils` and injecting the `"i686-linux"` system would resolve this issue:

- https://github.com/danth/stylix/blob/94d70292d0c687ebacb65d00bd516cbefa18d3ca/flake.nix#L61-L67

- > ### `defaultSystems :: [<system>]`
  >
  > The list of systems to use in `eachDefaultSystem` and `simpleFlake`.
  >
  > The default values are `["x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin"]`.
  >
  > -- https://github.com/numtide/flake-utils/blob/b1d9ab70662946ef0850d488da1c9019f3a9752a/README.md

**Comment by trueNAHO** [comment]
I already have a working PR. Once it is cleaned up I can submit it for review (tomorrow).

Coincidentally, the PR publicly interfaces an overridable list of supported architectures.

**Comment by danth** [comment]
I didn't think it was worth the extra dependency for something which could be implemented fairly easily using functions from the nixpkgs library.

Admittedly things have changed in both Stylix and flake-utils since that commit; there may also be additions to the nixpkgs library which could be useful here.
