### ISSUE TITLE
GDM not themed when Gnome is disabled

### ISSUE THREAD

**Issue by Kasper24** [danth/stylix#596]
This line is the reason why, I wonder if there's a need for it?
https://github.com/danth/stylix/blob/33a2eff15181e557bb6dd9d2073b90f7d218975d/modules/gnome/nixos.nix#L15

**Comment by trueNAHO** [comment]
> This line is the reason why, I wonder if there's a need for it?
>
> https://github.com/danth/stylix/blob/33a2eff15181e557bb6dd9d2073b90f7d218975d/modules/gnome/nixos.nix#L15

Since the introduction of this guard in commit 46899f291b8a ("Style GNOME shell :sparkles:") the convention to enable Stylix modules has slightly changed.

Considering the discussions in https://github.com/danth/stylix/issues/543 we may want to remove the `config.services.xserver.desktopManager.gnome.enable` guard.

Feel free to submit a PR.
