### ISSUE TITLE
Waybar style is unreadable with ayu-dark

### ISSUE THREAD

**Issue by lovesegfault** [danth/stylix#75]
The generated waybar style with `ayu-dark` theme is just about unusable. Here's how it looks on my system:
![image](https://user-images.githubusercontent.com/7243783/228544222-f61ddd4c-b549-4b39-abd1-02e85b03bf6f.png)

Compare this with my previous hand-rolled ayu-dark style:
![image](https://user-images.githubusercontent.com/7243783/228544857-208c263c-d124-4dbf-a858-0ca0836a17f6.png)

IMO, this suggests more work is needed to enable the target for all users.

**Comment by lovesegfault** [comment]
cc. @SomeGuyNamedMy

**Comment by danth** [comment]
I think the issue is that the accent colours (`base09` to `base0F`) are not guaranteed to contrast with the foreground colour (`base05`).

A few options we could choose from:

- Change the text to `base00` when an accent is used as the background
- Remove accent colours used as backgrounds and colour the text instead
- Remove accent colours entirely

**Comment by SomeGuyNamedMy** [comment]
my bad just noticed i missed some modules as well, will fix later today, made the mistake of just testing my own setup.

**Comment by SomeGuyNamedMy** [comment]
whats everyone's opinion on adding and option to disable accents by side in the module?

**Comment by danth** [comment]
I would have an option, as some people will prefer a simpler look.

**Comment by SomeGuyNamedMy** [comment]
what do we want the options to default to?
